apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-service-nugo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-service-nugo
    app.kubernetes.io/part-of: assisted-service
  name: assisted-service-nugo
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: assisted-service-nugo
status:
  loadBalancer: {}
